name: Build FFmpeg with x264 for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.5
      
    - name: Setup environment variables
      run: |
        echo "TT=armv7a-linux-androideabi" >> $GITHUB_ENV
        echo "NDK=/usr/local/lib/android/sdk/ndk/25.2.9519653" >> $GITHUB_ENV
        

    - name: Download FFmpeg source
      run: |
        wget -O - https://www.ffmpeg.org/releases/ffmpeg-7.0.1.tar.xz | tar -xJv -C $GITHUB_WORKSPACE

    - name: 444 content
      run: |
        grep -Ri "opengl" $GITHUB_WORKSPACE/ffmpeg-7.0.1
        
    
    - name: Modify configure script for OpenGL ES
      run: |
        sed -i '/enabled opengl            && { check_lib opengl GL\/glx.h glXGetProcAddress "-lGL" ||/,/                               }/c\
        enabled opengl            && { check_lib opengl "GLES2/gl2.h" glGetError "-lGLESv2" || die "ERROR: opengl not found."; }' configure
    
    - name: Print FFmpeg configure script content
      run: |
        cd $GITHUB_WORKSPACE/ffmpeg-7.0.1
        grep -A 5 -B 2 "enabled opengl" configure
        cat configure
    
    - name: 查一
      run: |
        ls -R /usr/local/lib/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
        find $NDK -name "*.pc"
    
    - name: 查2
      run: |
        find /usr/local/lib/android/sdk/ndk/25.2.9519653 -name libGLESv2.so
    
    - name: Copy gltransition filter source
      if: false
      run: |
        cp $GITHUB_WORKSPACE/vf_gltransition.c $GITHUB_WORKSPACE/ffmpeg-7.0.1/libavfilter/
        # 检查文件是否成功复制
        ls $GITHUB_WORKSPACE/ffmpeg-7.0.1/libavfilter/vf_gltransition.c
        ls $NDK/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/24
        find /usr/local/lib/android/sdk/ndk/25.2.9519653 -name pkgconfig
        find /usr/local/lib/android/sdk/ndk/25.2.9519653 -name .pc
        
        find /usr/local/lib/android/sdk/ndk/25.2.9519653 -name libGLESv2.so
    
    - name: Apply gltransition patch
      if: false
      run: |
        cd $GITHUB_WORKSPACE/ffmpeg-7.0.1
        git apply $GITHUB_WORKSPACE/ffmpeg.diff
        # 检查是否有未应用的修改
        git diff --exit-code # 如果没有输出，说明补丁已成功应用
    
    - name: 显示可用的FFmpeg配置选项
      if: false
      run: |
        cd $GITHUB_WORKSPACE/ffmpeg-7.0.1
        cp $GITHUB_WORKSPACE/vf_gltransition.c libavfilter/
        ls libavfilter/vf_gltransition.c
        ./configure --help
    
    - name: Customize FFmpeg banner in opt_common.c with green color
      run: |
        cd $GITHUB_WORKSPACE/ffmpeg-7.0.1
        BUILD_DATE=$(date +"%Y-%m-%d")
        sed -i '/void show_banner(int argc, char \*\*argv, const OptionDef \*options)/,/^}/c\
        void show_banner(int argc, char **argv, const OptionDef *options) {\n\
        av_log(NULL, AV_LOG_INFO, "FFmpeg %s - arm static build © 2000-2024 FFmpeg Team.\\nBuilt by pdahd (https://github.com/pdahd) on %s.\\n", FFMPEG_VERSION, "'$BUILD_DATE'");\n\
        }' fftools/opt_common.c
    
    - name: Compile and install x264 for armv7a
      run: |
        git clone https://code.videolan.org/videolan/x264.git
        cd x264
        patch -p0 < ../x264_fixes.patch
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        export SYSROOT=$TOOLCHAIN/sysroot 
        export CC=$TOOLCHAIN/bin/${TT}24-clang
        export CXX=$TOOLCHAIN/bin/${TT}24-clang++
        export CROSS_PREFIX=$TOOLCHAIN/bin/llvm-
        export CFLAGS="-DANDROID -Wall -fPIC" 
        export PREFIX=$GITHUB_WORKSPACE/exlibs
        export HOST=$TT
        
        ./configure --prefix="$PREFIX" \
                    --enable-static \
                    --enable-pic \
                    --disable-asm \
                    --host="$HOST" \
                    --cross-prefix="$CROSS_PREFIX" \
                    --sysroot="$SYSROOT" \
                    --extra-cflags="$CFLAGS"
        make -j$(nproc)
        make install

    - name: Configure FFmpeg for armv7a with x264
      run: |
        export NDK=/usr/local/lib/android/sdk/ndk/25.2.9519653
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        export SYSROOT=$TOOLCHAIN/sysroot 
        export CC=$TOOLCHAIN/bin/${TT}24-clang
        export CXX=$TOOLCHAIN/bin/${TT}24-clang++
        export CROSS_PREFIX=$TOOLCHAIN/bin/llvm-
        export PKG_CONFIG=/usr/bin/pkg-config
        export PREFIX=$GITHUB_WORKSPACE/2024
      
        cd $GITHUB_WORKSPACE/ffmpeg-7.0.1
        cp $GITHUB_WORKSPACE/vf_gltransition.c libavfilter/
        echo "vf_gltransition.c copied to: $(pwd)/libavfilter/vf_gltransition.c"
        git apply $GITHUB_WORKSPACE/ffmpeg.diff
        echo "Patch applied successfully"
        ./configure \
          --arch=arm \
          --cc="$CC" \
          --cxx="$CXX" \
          --cross-prefix="$CROSS_PREFIX" \
          --disable-indevs \
          --disable-outdevs \
          --disable-static \
          --disable-symver \
          --pkg-config="$PKG_CONFIG" \
          --enable-filter=gltransition \
          --enable-shared \
          --enable-opengl \
          --enable-mediacodec \
          --enable-version3 \
          --enable-jni \
          --enable-indev=lavfi \
          --enable-cross-compile \
          --enable-neon \
          --enable-gpl \
          --prefix="$PREFIX" \
          --target-os=android \
          --extra-cflags="-I$NDK/sysroot/usr/include/GLES2" \
          --extra-ldflags="-L$NDK/sysroot/usr/lib/arm-linux-androideabi/24 -lGLESv2" \
          --disable-vulkan \
          --sysroot="$SYSROOT" 

    - name: Upload config.log
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: config-log
        path: ffmpeg-7.0.1/ffbuild/config.log
        if-no-files-found: warn
