name: Build FFmpeg for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: r25c
      ANDROID_API_LEVEL: 21
      TERMUX_PREFIX: /data/data/com.termux/files/usr

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Download and set up Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-${{ env.ANDROID_NDK_VERSION }}-linux.zip
        unzip android-ndk-${{ env.ANDROID_NDK_VERSION }}-linux.zip
        export ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk-${{ env.ANDROID_NDK_VERSION }}
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
        echo "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          automake \
          build-essential \
          cmake \
          git \
          libtool \
          pkg-config \
          texinfo \
          wget \
          yasm \
          zlib1g-dev

    - name: Configure and build FFmpeg
      run: |
        git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
        cd ffmpeg
        export TOOLCHAIN=${{ env.ANDROID_NDK_HOME }}/toolchains/llvm/prebuilt/linux-x86_64
        export TARGET=aarch64-linux-android
        export API=${{ env.ANDROID_API_LEVEL }}
        export CC=$TOOLCHAIN/bin/$TARGET$API-clang
        export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
        export LD=$TOOLCHAIN/bin/$TARGET-ld
        export CFLAGS="-isysroot $TOOLCHAIN/sysroot -I$TOOLCHAIN/sysroot/usr/include -D__ANDROID_API__=$API -fPIC"
        export LDFLAGS="-L$TOOLCHAIN/lib64 -L$TOOLCHAIN/sysroot/usr/lib -lc -lm -ldl -llog"
        ./configure \
          --prefix=${{ env.TERMUX_PREFIX }} \
          --target-os=android \
          --arch=arm64 \
          --cross-prefix=$TOOLCHAIN/bin/$TARGET$API- \
          --sysroot=$TOOLCHAIN/sysroot \
          --enable-cross-compile \
          --disable-static \
          --enable-shared \
          --disable-everything \
          --enable-small \
          --enable-protocols \
          --enable-demuxers \
          --enable-muxers \
          --enable-parsers \
          --enable-decoders \
          --enable-encoders
        make -j$(nproc)
        make install
      continue-on-error: true

    - name: Upload config.log
      uses: actions/upload-artifact@v2
      with:
        name: config-log
        path: ffmpeg/ffbuild/config.log
