name: Build FFmpeg for Android (Termux)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CC: /usr/local/lib/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24-clang
  CXX: /usr/local/lib/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24-clang++
  CROSS_PREFIX: /usr/local/lib/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-
  SYSROOT: /usr/local/lib/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot
  H: "wget --header=\"Accept: application/vnd.github.v3.raw\" -O "
  FFMPEG: ${{ github.workspace }}/ffmpeg-7.0.1
  FFLIB: ${{ github.workspace }}/2024/lib
  PREFIX: ${{ github.workspace }}/2024
  U: "https://api.github.com/repos"
  PKG_CONFIG: /usr/bin/pkg-config
  HOST: armv7a-linux-androideabi
  LOCLIB: /usr/local/lib

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.5

    - name: Prepare Source Code
      run: |
        wget -O - https://www.ffmpeg.org/releases/ffmpeg-7.0.1.tar.xz | tar -xJv -C $GITHUB_WORKSPACE
        git clone https://code.videolan.org/videolan/x264.git

    - name: Apply Patches and Compile x264
      run: |
        cd x264
        ${{ env.H }}x264_fixes.patch ${{ env.U }}/pdahd/pda/contents/x264_fixes.patch
        patch -p0 < x264_fixes.patch
        ./configure --extra-cflags="-DANDROID -Wall -fPIC" \
                    --cross-prefix=$CROSS_PREFIX \
                    --sysroot=$SYSROOT \
                    --host=$HOST \
                    --enable-shared \
                    --enable-pic \
                    --disable-asm 
        make -j$(nproc)
        sudo make install

    - name: Patch, Configure and Prepare FFmpeg
      run: |
        cd $FFMPEG
        BUILD_DATE=$(date +"%Y-%m-%d")
        ${{ env.H }}libavfilter/xfade-easing.h ${{ env.U }}/scriptituk/xfade-easing/contents/src/xfade-easing.h
        ${{ env.H }}libavfilter/vf_xfade.c ${{ env.U }}/scriptituk/xfade-easing/contents/src/vf_xfade.c
        sed -i '/void show_banner(int argc, char \*\*argv, const OptionDef \*options)/,/^}/c\
            void show_banner(int argc, char **argv, const OptionDef *options) {
            av_log(NULL, AV_LOG_INFO, "\n-------------------------------------------------------------\\n");
            av_log(NULL, AV_LOG_INFO, "FFmpeg %s (armv7-a custom build) © 2000-2024 FFmpeg Team.\\n", FFMPEG_VERSION);
            av_log(NULL, AV_LOG_INFO, "Built by pdahd (https://github.com/pdahd) on %s.\\n", "'"$BUILD_DATE"'");
            av_log(NULL, AV_LOG_INFO, "-------------------------------------------------------------\\n");
            }' fftools/opt_common.c
        
        ./configure --cross-prefix=$CROSS_PREFIX \
                    --pkg-config=$PKG_CONFIG \
                    --target-os=android \
                    --sysroot=$SYSROOT \
                    --prefix=$PREFIX \
                    --cpu=armv7-a \
                    --arch=arm \
                    --cxx=$CXX \
                    --cc=$CC \
                    --enable-cross-compile \
                    --enable-indev=lavfi \
                    --enable-mediacodec \
                    --enable-version3 \
                    --enable-libx264 \
                    --enable-shared \
                    --enable-neon \
                    --enable-jni \
                    --enable-gpl \
                    --disable-outdevs \
                    --disable-vulkan \
                    --disable-indevs \
                    --disable-static \
                    --disable-symver 

    - name: Build and Install FFmpeg
      run: |
        cd $FFMPEG
        make -j$(nproc)
        make install

    - name: List files in lib directory
      run: |
        cp $LOCLIB/libx264.so.164 $FFLIB
        ls -l $FFLIB

    - name: Upload FFmpeg Build as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-armeabi-v7a
        path: 2024/**
