name: Build FFmpeg with x264 for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup environment variables
      run: |
        echo "ANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/25.2.9519653" >> $GITHUB_ENV
        echo "API=21" >> $GITHUB_ENV

    - name: Download FFmpeg source
      run: |
        wget -O - https://www.ffmpeg.org/releases/ffmpeg-6.1.1.tar.xz | tar -xJv -C $GITHUB_WORKSPACE

    - name: Compile and install x264
      run: |
        INSTALL_DIR=$GITHUB_WORKSPACE/external_libs
        
        mkdir -p $INSTALL_DIR

        git clone https://code.videolan.org/videolan/x264.git
        cd x264
        
        patch -p0 < ../x264_fixes.patch
        
        export NDK=$ANDROID_NDK_ROOT
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        export SYSROOT=$TOOLCHAIN/sysroot
        export TOOLNAME_BASE="aarch64-linux-android"
        export COMPILER_BASE="aarch64-linux-android"
        export HOST="aarch64-linux-android"
        export CROSS_PREFIX=$TOOLCHAIN/bin/$TOOLNAME_BASE-
        export CC=$TOOLCHAIN/bin/$COMPILER_BASE$API-clang
        export CXX=$TOOLCHAIN/bin/$COMPILER_BASE$API-clang++
        export AR=$TOOLCHAIN/bin/llvm-ar
        export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
        export STRINGS=$TOOLCHAIN/bin/llvm-strings
        export CFLAGS="-DANDROID -Wall -fPIC"
    
        ./configure --prefix=$INSTALL_DIR \
                    --enable-static \
                    --enable-pic \
                    --disable-asm \
                    --host=$HOST \
                    --cross-prefix=$CROSS_PREFIX \
                    --sysroot=$SYSROOT \
                    --extra-cflags="$CFLAGS"
        make -j$(nproc)
        make install
        
        echo "Listing files for x264:"
        find $INSTALL_DIR -type f
        
        echo "X264_INCLUDE=$GITHUB_WORKSPACE/external_libs/include" >> $GITHUB_ENV
        echo "X264_LIB=$GITHUB_WORKSPACE/external_libs/lib" >> $GITHUB_ENV

    - name: Configure FFmpeg for arm64-v8a with x264
      run: |
        export ARCH=aarch64
        export PREFIX=$GITHUB_WORKSPACE/android/arm64-v8a
        export TERMUX=aarch64-linux-android
        export NDK=$ANDROID_NDK_ROOT
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        export SYSROOT=$TOOLCHAIN/sysroot
        export CC=$TOOLCHAIN/bin/$TERMUX$API-clang
        export CXX=$TOOLCHAIN/bin/$TERMUX$API-clang++
        export CROSS_PREFIX=$TOOLCHAIN/bin/$TERMUX-
        export AR=$TOOLCHAIN/bin/llvm-ar
        export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
        export NM=$TOOLCHAIN/bin/llvm-nm
        export PKG_CONFIG=/usr/bin/pkg-config
        export STRIP=$TOOLCHAIN/bin/llvm-strip
         
        cd $GITHUB_WORKSPACE/ffmpeg-6.1.1
        ./configure \
          --arch="$ARCH" \
          --nm="$NM" \
          --cc="$CC" \
          --cxx="$CXX" \
          --strip="$STRIP" \
          --cross-prefix="$CROSS_PREFIX" \
          --disable-indevs \
          --disable-outdevs \
          --disable-static \
          --disable-symver \
          --pkg-config="$PKG_CONFIG" \
          --enable-cross-compile \
          --enable-libx264 \
          --enable-neon \
          --enable-gpl \
          --enable-shared \
          --prefix="$PREFIX" \
          --target-os=android \
          --extra-cflags="-I${X264_INCLUDE}" \
          --extra-ldflags="-L${X264_LIB}" \
          --disable-vulkan \
          --sysroot="$SYSROOT" \
          --disable-libfdk-aac

    - name: Compile FFmpeg
      run: |
        cd $GITHUB_WORKSPACE/ffmpeg-6.1.1
        make -j$(nproc)
        make install
