name: Build FFmpeg with x264 for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.5
      
    - name: Setup environment variables
      run: |
        echo "API=24" >> $GITHUB_ENV
        echo "TT=armv7a-linux-androideabi" >> $GITHUB_ENV
        echo "NDK=/usr/local/lib/android/sdk/ndk/25.2.9519653" >> $GITHUB_ENV
        echo "TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64" >> $GITHUB_ENV
        echo "CFLAGS=-DANDROID -Wall -fPIC" >> $GITHUB_ENV
        echo "INSTALL_DIR=$GITHUB_WORKSPACE/exlibs" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$GITHUB_WORKSPACE/exlibs/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

    - name: Download FFmpeg source
      run: |
        wget -O - https://www.ffmpeg.org/releases/ffmpeg-7.0.1.tar.xz | tar -xJv -C $GITHUB_WORKSPACE

    - name: Compile and install x264 for armv7a
      if: false
      run: |
        git clone https://code.videolan.org/videolan/x264.git
        cd x264
        patch -p0 < ../x264_fixes.patch
       
        ./configure \ 
          --prefix=$INSTALL_DIR \
          --cc="$CC" \
          --cxx="$CXX" \
          --enable-static \
          --enable-pic \
          --disable-asm \
          --host="$TT" \
          --cross-prefix="$CROSS_PREFIX" \
          --sysroot=$SYSROOT \
          --extra-cflags="$CFLAGS"
        make -j$(nproc)
        make install

    - name: Configure FFmpeg for armv7a with x264
      run: |
        export PREFIX=$GITHUB_WORKSPACE/2024
        export SYSROOT=$TOOLCHAIN/sysroot 
        export CC=$TOOLCHAIN/bin/$TT$API-clang
        export CXX=$TOOLCHAIN/bin/$TT$API-clang++
        export CROSS_PREFIX=$TOOLCHAIN/bin/llvm-
        export PKG_CONFIG=/usr/bin/pkg-config
        
        cd $GITHUB_WORKSPACE/ffmpeg-7.0.1
        ./configure \
          --arch=arm \
          --cc="$CC" \
          --cxx="$CXX" \
          --cross-prefix="$CROSS_PREFIX" \
          --disable-indevs \
          --disable-outdevs \
          --disable-shared \
          --disable-symver \
          --pkg-config="$PKG_CONFIG" \
          --enable-static \
          --enable-cross-compile \
          --enable-neon \
          --enable-gpl \
          --prefix="$PREFIX" \
          --target-os=android \
          --disable-vulkan \
          --sysroot="$SYSROOT" \
          --disable-libfdk-aac

    - name: Build FFmpeg for armv7a
      if: false
      run: |
        cd $GITHUB_WORKSPACE/ffmpeg-7.0.1
        make -j$(nproc)
        make install

    - name: Upload FFmpeg Build Artifact for armv7a
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-armeabi-v7a
        path: ${{ github.workspace }}/2024/**
