name: Build FFmpeg for Android (Termux)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CC: /usr/local/lib/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24-clang
  CXX: /usr/local/lib/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24-clang++
  CROSS_PREFIX: /usr/local/lib/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-
  SYSROOT: /usr/local/lib/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/sysroot
  HOST: armv7a-linux-androideabi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.5
    
    - name: Prepare Source Code
      run: |
        git clone https://code.videolan.org/videolan/x264.git
        for url in https://www.ffmpeg.org/releases/ffmpeg-7.0.1.tar.xz \
        https://github.com/mstorsjo/fdk-aac/archive/refs/tags/v2.0.3.tar.gz; do
        if [[ "$url" == *.tar.xz ]]; then
        wget -O - "$url" | tar -xJv 
        elif [[ "$url" == *.tar.gz ]]; then
        wget -O - "$url" | tar -xzv 
        elif [[ "$url" == *.tar.bz2 ]]; then
        wget -O - "$url" | tar xjvf -
        elif [[ "$url" == *.zip ]]; then
        wget "$url" ; unzip *.zip
        fi
        done
        
    - name: Compile x264
      run: |
        cd x264
        sed -i '/unsigned int i_sign;/a\
        i_sign = 1;\
        printf("i_sign: %u\\n", i_sign);
        ' encoder/cavlc.c
        ./configure --extra-cflags="-DANDROID -Wall -fPIC" \
                    --cross-prefix=$CROSS_PREFIX \
                    --sysroot=$SYSROOT \
                    --host=$HOST \
                    --enable-shared \
                    --enable-pic \
                    --disable-asm 
        make -j$(nproc)
        sudo make install  
    
    - name: Compile libfdk-aac
      run: |
        cd fdk-aac-2.0.3
        ./autogen.sh
        sed -i '/#include "log\/log.h"/d; /android_errorWriteLog(0x534e4554, "112160868");/d' libSBRdec/src/lpp_tran.cpp
        sed -i 's/WARNING: using cross tools not prefixed with host triplet/cross tools prefix has been updated to llvm-/g' configure
        sed -i '/ac_tool_prefix=/ { N; c\
        ac_tool_prefix="llvm-" 
        }' configure
        ./configure --enable-shared --host=$HOST --with-pic
        make -j$(nproc)
        sudo make install
    
    - name: Configure FFmpeg and Enhance Filters
      run: |
        cd ffmpeg-7.0.1
        BUILD_DATE=$(date +"%Y-%m-%d")
        sed -i '/void show_banner(int argc, char \*\*argv, const OptionDef \*options)/,/^}/c\
        void show_banner(int argc, char **argv, const OptionDef *options) {\n\
        av_log(NULL, AV_LOG_ERROR, "-------------------------------------------------------------------\\n");\n\
        av_log(NULL, AV_LOG_INFO | (AV_CLASS_CATEGORY_SWRESAMPLER << 8), "FFmpeg %s (armv7-a custom build) © 2000-2024 FFmpeg Developers.\\n", FFMPEG_VERSION);\n\
        av_log(NULL, AV_LOG_INFO | (AV_CLASS_CATEGORY_SWRESAMPLER << 8), "Built by pdahd (https://github.com/pdahd/FFmpegAct) on %s.\\n", "'$BUILD_DATE'");\n\
        av_log(NULL, AV_LOG_ERROR, "-------------------------------------------------------------------\\n");\n\
        }' fftools/opt_common.c
        for file in xfade-easing.h vf_xfade.c; do
        curl -L -o "libavfilter/${file}" "https://raw.githubusercontent.com/scriptituk/xfade-easing/main/src/${file}"
        done
        ./configure --pkg-config="/usr/bin/pkg-config" \
                    --prefix="$GITHUB_WORKSPACE/2024" \
                    --cross-prefix=$CROSS_PREFIX \
                    --target-os=android \
                    --sysroot=$SYSROOT \
                    --cpu=armv7-a \
                    --arch=arm \
                    --cxx=$CXX \
                    --cc=$CC \
                    --enable-cross-compile \
                    --enable-indev=lavfi \
                    --enable-libfdk-aac \
                    --enable-mediacodec \
                    --enable-version3 \
                    --enable-nonfree \
                    --enable-libx264 \
                    --enable-shared \
                    --enable-neon \
                    --enable-jni \
                    --enable-gpl \
                    --disable-outdevs \
                    --disable-vulkan \
                    --disable-indevs \
                    --disable-static \
                    --disable-symver 

    - name: Build and Install FFmpeg
      run: |
        cd ffmpeg-7.0.1
        make -j$(nproc)
        make install

    - name: List files in lib directory
      run: |
        LIBS=(libx264.so.164 \
              libfdk-aac.so)
        for lib in "${LIBS[@]}"; do
        cp "/usr/local/lib/$lib" "2024/lib"
        done
        ls -l 2024/lib

    - name: Upload FFmpeg Build as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-armeabi-v7a
        path: 2024/**
