name: Build FFmpeg for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: r21e
      ANDROID_API_LEVEL: 21
      TERMUX_PREFIX: /data/data/com.termux/files/usr

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Download and set up Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip
        unzip android-ndk-${ANDROID_NDK_VERSION}-linux-x86_64.zip
        export ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk-${ANDROID_NDK_VERSION}
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
        echo "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          automake \
          build-essential \
          cmake \
          git \
          libtool \
          pkg-config \
          texinfo \
          wget \
          yasm \
          zlib1g-dev

    - name: Configure and build FFmpeg
      run: |
        git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
        cd ffmpeg
        ./configure \
          --prefix=$TERMUX_PREFIX \
          --target-os=android \
          --arch=arm64 \
          --cross-prefix=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android- \
          --sysroot=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
          --enable-cross-compile \
          --disable-static \
          --enable-shared \
          --disable-everything \
          --enable-small \
          --enable-protocols \
          --enable-demuxers \
          --enable-muxers \
          --enable-parsers \
          --enable-decoders \
          --enable-encoders
        make -j$(nproc)
        make install

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ffmpeg-android
        path: ffmpeg
