name: Build FFmpeg for Termux

on:
  push:
    branches:
      - main # 触发构建的分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        env:
          ANDROID_NDK_VERSION: r26b # 根据你的需求修改NDK版本
          TERMUX_ARCH: arm
          TERMUX_HOST_PLATFORM: arm-linux-androideabi
        run: |
          # 下载并解压Android NDK
          wget -q https://dl.google.com/android/repository/android-ndk-$ANDROID_NDK_VERSION-linux.zip
          unzip -q android-ndk-$ANDROID_NDK_VERSION-linux.zip
          export ANDROID_NDK=$GITHUB_WORKSPACE/android-ndk-$ANDROID_NDK_VERSION

          # 设置工具链路径
          export PATH=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          export AS=arm-linux-androideabi-clang
          export CC=arm-linux-androideabi-clang
          export CXX=arm-linux-androideabi-clang++
          export NM=llvm-nm
          export PKG_CONFIG=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/pkg-config
          export STRIP=llvm-strip

      - name: Download FFmpeg source code
        run: wget -q https://www.ffmpeg.org/releases/ffmpeg-${{ env.TERMUX_PKG_VERSION }}.tar.xz

      - name: Extract FFmpeg source code
        run: tar -xf ffmpeg-${{ env.TERMUX_PKG_VERSION }}.tar.xz

      - name: Configure FFmpeg
        working-directory: ffmpeg-${{ env.TERMUX_PKG_VERSION }}
        run: |
          ./configure \
            --arch=armeabi-v7a \
            --as="$AS" \
            --cc="$CC" \
            --cxx="$CXX" \
            --nm="$NM" \
            --pkg-config="$PKG_CONFIG" \
            --strip="$STRIP" \
            --cross-prefix="${TERMUX_HOST_PLATFORM}-" \
            --disable-indevs \
            --disable-outdevs \
            --enable-indev=lavfi \
            --disable-static \
            --disable-symver \
            --enable-cross-compile \
            --enable-gpl \
            --enable-version3 \
            --enable-jni \
            --enable-shared \
            --prefix="$GITHUB_WORKSPACE/ffmpeg-build" \
            --target-os=android \
            --extra-libs="-landroid-glob" \
            --disable-vulkan \
            --enable-neon \
            #  --disable-libfdk-aac \
            #  精简配置，根据需要选择开启或关闭以下功能
            --disable-doc \
            --disable-programs \
            --disable-avdevice \
            --disable-postproc \
            --disable-debug \
            --disable-optimizations \
            --enable-small

      - name: Build FFmpeg
        working-directory: ffmpeg-${{ env.TERMUX_PKG_VERSION }}
        run: make -j$(nproc)

      - name: Install FFmpeg
        working-directory: ffmpeg-${{ env.TERMUX_PKG_VERSION }}
        run: make install

      - name: Upload FFmpeg executable
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-armeabi-v7a
          path: ffmpeg-build/bin/ffmpeg
