name: Build FFmpeg for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: r21e
      ANDROID_HOME: ${{ runner.temp }}/android-sdk
      NDK_HOME: ${{ runner.temp }}/android-ndk-$ANDROID_NDK_VERSION
      SDK_URL: https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
      NDK_URL: https://dl.google.com/android/repository/android-ndk-$ANDROID_NDK_VERSION-linux-x86_64.zip

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Download and set up Android SDK
      run: |
        mkdir -p $ANDROID_HOME
        wget $SDK_URL -O sdk-tools.zip
        unzip -q sdk-tools.zip -d $ANDROID_HOME
        yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
        $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"

    - name: Download and set up Android NDK
      run: |
        wget $NDK_URL -O ndk.zip
        unzip -q ndk.zip -d ${{ runner.temp }}
        mv ${{ runner.temp }}/android-ndk-$ANDROID_NDK_VERSION $NDK_HOME

    - name: Set up environment variables
      run: |
        echo "ANDROID_NDK_ROOT=$NDK_HOME" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$NDK_HOME" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "PATH=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Clone FFmpeg repository
      run: git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg

    - name: Build FFmpeg for Android
      run: |
        cd ffmpeg
        ./configure \
          --prefix=$ANDROID_HOME \
          --target-os=android \
          --arch=arm64 \
          --cross-prefix=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android- \
          --sysroot=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
          --enable-cross-compile \
          --disable-static \
          --enable-shared \
          --disable-everything \
          --enable-small \
          --enable-protocols \
          --enable-demuxers \
          --enable-muxers \
          --enable-parsers \
          --enable-decoders \
          --enable-encoders
        make -j$(nproc)
        make install
