name: Build FFmpeg with x264 for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NDK_ROOT: /usr/local/lib/android/sdk/ndk/25.2.9519653
      INST_DIR: ${{ github.workspace }}/external_libs
      PREFIX: ${{ github.workspace }}/android/armeabi-v7a

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.5

    - name: Setup environment variables
      run: |
        echo "PKG_CONFIG_PATH=$INST_DIR/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "NDK=${{ env.NDK_ROOT }}" >> $GITHUB_ENV
        echo "T_PLAT=armv7a-linux-androideabi" >> $GITHUB_ENV
        echo "API=21" >> $GITHUB_ENV
        echo "ARCH=arm" >> $GITHUB_ENV

    - name: Download FFmpeg source
      run: |
        wget -O - https://www.ffmpeg.org/releases/ffmpeg-7.0.1.tar.xz | tar -xJv -C $GITHUB_WORKSPACE

    - name: Compile and install x264 for armv7a
      run: |
        mkdir -p $INST_DIR
        git clone https://code.videolan.org/videolan/x264.git
        cd x264
        
        patch -p0 < ../x264_fixes.patch
        
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        export SYSROOT=$TOOLCHAIN/sysroot
        export T_NAME="armv7a-linux-androideabi"
        export C_BASE="armv7a-linux-androideabi"
        export HOST="armv7a-linux-androideabi"
        export CROSS_PREFIX=$TOOLCHAIN/bin/$T_NAME-
        export CC=$TOOLCHAIN/bin/$C_BASE$API-clang
        export CXX=$TOOLCHAIN/bin/$C_BASE$API-clang++
        export AR=$TOOLCHAIN/bin/llvm-ar
        export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
        export STRINGS=$TOOLCHAIN/bin/llvm-strings
        export CFLAGS="-DANDROID -Wall -fPIC"
    
        ./configure --prefix=$INSTALL_DIR \
                    --enable-static \
                    --enable-pic \
                    --disable-asm \
                    --host=$HOST \
                    --cross-prefix=$CROSS_PREFIX \
                    --sysroot=$SYSROOT \
                    --extra-cflags="$CFLAGS"
        make -j$(nproc)
        make install

    - name: Configure FFmpeg for armv7a with x264
      run: |
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        export SYSROOT=$TOOLCHAIN/sysroot
        export CC=$TOOLCHAIN/bin/$T_PLAT$API-clang
        export CXX=$TOOLCHAIN/bin/$T_PLAT$API-clang++
        export CROSS_PREFIX=$TOOLCHAIN/bin/$T_PLAT-
        export AR=$TOOLCHAIN/bin/llvm-ar
        export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
        export NM=$TOOLCHAIN/bin/llvm-nm
        export PKG_CONFIG=/usr/bin/pkg-config
        export STRIP=$TOOLCHAIN/bin/llvm-strip
        
        cd $GITHUB_WORKSPACE/ffmpeg-7.0.1
        ./configure \
          --arch="$ARCH" \
          --nm="$NM" \
          --cc="$CC" \
          --ar="$AR" \
          --cxx="$CXX" \
          --ranlib="$RANLIB" \
          --strip="$STRIP" \
          --cross-prefix="$CROSS_PREFIX" \
          --disable-indevs \
          --disable-outdevs \
          --disable-shared \
          --disable-symver \
          --pkg-config="$PKG_CONFIG" \
          --enable-static \
          --enable-cross-compile \
          --enable-libx264 \
          --enable-neon \
          --enable-gpl \
          --prefix="$PREFIX" \
          --target-os=android \
          --disable-vulkan \
          --sysroot="$SYSROOT" \
          --disable-libfdk-aac

    - name: Build FFmpeg for armv7a
      run: |
        cd $GITHUB_WORKSPACE/ffmpeg-7.0.1
        make -j$(nproc)
        make install

    - name: Upload FFmpeg Build Artifact for armv7a
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-armeabi-v7a
        path: ${{ github.workspace }}/android/armeabi-v7a/**
