name: Build FFmpeg for Termux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: r21e
      ANDROID_API_LEVEL: 21
      ARCH: armeabi-v7a
      PREFIX: /data/data/com.termux/files/usr

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Download and extract Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-${{ env.ANDROID_NDK_VERSION }}-linux-x86_64.zip
        unzip android-ndk-${{ env.ANDROID_NDK_VERSION }}-linux-x86_64.zip
        export ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk-${{ env.ANDROID_NDK_VERSION }}
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake build-essential cmake git libtool pkg-config texinfo zlib1g-dev yasm

    - name: Install gas-preprocessor
      run: |
        git clone https://github.com/FFmpeg/gas-preprocessor
        sudo cp gas-preprocessor/gas-preprocessor.pl /usr/local/bin/
        sudo chmod +x /usr/local/bin/gas-preprocessor.pl

    - name: Set up environment variables
      run: |
        export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
        export TARGET=armv7a-linux-androideabi
        export API=${{ env.ANDROID_API_LEVEL }}
        export AR=$TOOLCHAIN/bin/arm-linux-androideabi-ar
        export AS=$TOOLCHAIN/bin/arm-linux-androideabi-as
        export CC=$TOOLCHAIN/bin/armv7a-linux-androideabi$API-clang
        export CXX=$TOOLCHAIN/bin/armv7a-linux-androideabi$API-clang++
        export LD=$TOOLCHAIN/bin/arm-linux-androideabi-ld
        export STRIP=$TOOLCHAIN/bin/arm-linux-androideabi-strip
        export NM=$TOOLCHAIN/bin/llvm-nm
        export CROSS_PREFIX=$TOOLCHAIN/bin/arm-linux-androideabi-
        export PATH="/usr/local/bin:$PATH"
        echo "TOOLCHAIN=$TOOLCHAIN" >> $GITHUB_ENV
        echo "TARGET=$TARGET" >> $GITHUB_ENV
        echo "API=$API" >> $GITHUB_ENV
        echo "AR=$AR" >> $GITHUB_ENV
        echo "AS=$AS" >> $GITHUB_ENV
        echo "CC=$CC" >> $GITHUB_ENV
        echo "CXX=$CXX" >> $GITHUB_ENV
        echo "LD=$LD" >> $GITHUB_ENV
        echo "STRIP=$STRIP" >> $GITHUB_ENV
        echo "NM=$NM" >> $GITHUB_ENV
        echo "CROSS_PREFIX=$CROSS_PREFIX" >> $GITHUB_ENV
        echo "PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV

    - name: Download FFmpeg source code
      run: |
        wget https://ffmpeg.org/releases/ffmpeg-6.1.1.tar.xz
        tar -xvf ffmpeg-6.1.1.tar.xz
        cd ffmpeg-6.1.1

    - name: Configure FFmpeg
      run: |
        cd ffmpeg-6.1.1
        ./configure \
          --prefix=${{ env.PREFIX }} \
          --target-os=android \
          --arch=${{ env.ARCH }} \
          --cc=$CC \
          --cxx=$CXX \
          --ld=$LD \
          --ar=$AR \
          --as=$AS \
          --nm=$NM \
          --strip=$STRIP \
          --cross-prefix=$CROSS_PREFIX \
          --disable-static \
          --enable-shared \
          --disable-indevs \
          --disable-outdevs \
          --disable-everything \
          --enable-small \
          --enable-cross-compile \
          --enable-gpl \
          --enable-version3 \
          --enable-libmp3lame \
          --enable-libx264 \
          --enable-libx265 \
          --enable-libvpx \
          --enable-libopus \
          --enable-libvorbis \
          --enable-libfreetype \
          --enable-libass \
          --enable-libdav1d \
          --enable-libwebp \
          --enable-libtheora \
          --enable-libsoxr \
          --enable-libvidstab \
          --enable-libzimg \
          --enable-libxml2 \
          --enable-libbluray \
          --enable-libopenmpt \
          --enable-libgme \
          --enable-libopencore-amrnb \
          --enable-libopencore-amrwb \
          --enable-librav1e \
          --enable-libsrt \
          --enable-libssh \
          --enable-libsvtav1 \
          --enable-libvo-amrwbenc \
          --enable-libv4l2 \
          --enable-libxvid \
          --enable-libzimg \
          --enable-neon

    - name: Build FFmpeg
      run: |
        cd ffmpeg-6.1.1
        make -j$(nproc)
        make install

    - name: Upload FFmpeg binary
      uses: actions/upload-artifact@v2
      with:
        name: ffmpeg-binary
        path: ${{ env.PREFIX }}/bin/ffmpeg
