name: Build FFmpeg with x264 and OpenSSL

on: [push]

jobs:
  build_ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            build-essential \
            cmake \
            git \
            libass-dev \
            libfdk-aac-dev \
            libmp3lame-dev \
            libopus-dev \
            libtheora-dev \
            libtool \
            libvorbis-dev \
            pkg-config \
            texinfo \
            wget \
            yasm \
            zlib1g-dev \
            nasm \
            libvpx-dev \
            libssl-dev \
            libx264-dev
      
      - name: Check for static libraries
        if: false
        run: |
          sudo apt-get install -y apt-file # Install apt-file if not already installed
          sudo apt-file update
          apt-file search libx264.a
          apt-file search libx265.a
          apt-file search libfdk-aac.a
          apt-file search libmp3lame.a
          apt-file search libopus.a
          apt-file search libtheora.a
          apt-file search libvorbis.a
          apt-file search libvpx.a
          apt-file search libssl.a
          apt-file search libz.a
          apt-file search libass.a # You might need libass-dev for static linking

      - name: Clone and build x265
        run: |
          git clone https://bitbucket.org/multicoreware/x265_git.git
          cd x265_git

          mkdir -p build/linux
          cd build/linux
    
          cmake -DENABLE_SHARED=OFF \
                -DENABLE_CLI=OFF \
                -DCMAKE_INSTALL_PREFIX=/usr \
                -DCMAKE_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu \
                -DCMAKE_INCLUDE_PATH=/usr/include \
                -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig \
                -S ../../source \
                -B .
          
          make -j$(nproc)
          sudo make install
      
      - name: Check installed libraries
        run: |
          echo "Checking installed libraries..."
          for lib in \
            libass-dev \
            libfdk-aac-dev \
            libmp3lame-dev \
            libopus-dev \
            libtheora-dev \
            libtool \
            libvorbis-dev \
            libvpx-dev \
            libx265 \
            libssl-dev \
            libx264-dev; do
              echo "Files included in $lib:"
              dpkg-query -L $lib  # 查询该库包含的文件
              echo ""
          done
      
      - name: Clone and build FFmpeg
        run: |
          git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git
          cd ffmpeg
          
          ./configure --enable-gpl \
            --enable-libx264 \
            --enable-libx265 \
            --enable-libfdk-aac \
            --enable-libmp3lame \
            --enable-libopus \
            --enable-libtheora \
            --enable-libvorbis \
            --enable-libvpx \
            --enable-openssl \
            --enable-nonfree \
            --enable-static \
            --disable-shared \
            --prefix=/usr/local/ff2024 \
            --extra-ldflags="-L/usr/lib/x86_64-linux-gnu -static" \
            --pkg-config-flags="--static"

          make -j$(nproc)
          sudo make install
          sudo ldconfig
          ldd /usr/local/ff2024/bin/ffmpeg || true
      
      - name: Clone FFmpeg
        if: false
        run: |
          git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git
          cd ffmpeg
          
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
          
          ./configure --enable-gpl --enable-libx264 --enable-libfdk-aac --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-openssl --enable-nonfree --enable-static --disable-shared --prefix=/usr/local/ff2024 --pkg-config-flags="--static" 

          make -j$(nproc)
          sudo make install
          sudo ldconfig
          
          ldd /usr/local/ff2024/bin/ffmpeg 
          
          sudo cp /lib/x86_64-linux-gnu/libvpx.so.7 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libssl.so.3 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libcrypto.so.3 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libx264.so.163 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libx265.so.199 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libfdk-aac.so.2 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libmp3lame.so.0 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libopus.so.0 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libtheoraenc.so.1 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libtheoradec.so.1 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libvorbis.so.0 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libvorbisenc.so.2 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libbz2.so.1.0 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libz.so.1 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/liblzma.so.5 /usr/local/ff2024/bin/
     
      - name: Verify FFmpeg installation
        run: |
          /usr/local/ff2024/bin/ffmpeg -version
          echo "Listing files in /usr/local/ff2024:"
          ls -R /usr/local/ff2024  
     
      - name: Upload FFmpeg as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg
          path: /usr/local/ff2024/bin/ffmpeg
