name: Build FFmpeg with x264 and OpenSSL

on: [push]

jobs:
  build_ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            build-essential \
            cmake \
            git \
            libass-dev \
            libfdk-aac-dev \
            libmp3lame-dev \
            libopus-dev \
            libtheora-dev \
            libtool \
            libvorbis-dev \
            texinfo \
            wget \
            yasm \
            zlib1g-dev \
            nasm \
            libvpx-dev \
            libssl-dev \
            libx264-dev
      
      - name: Clone and build x265
        run: |
          git clone https://bitbucket.org/multicoreware/x265_git.git
          cd x265_git/build/linux
    
          cmake -DENABLE_SHARED=ON -DENABLE_CLI=OFF ../../source
          
          make -j$(nproc)
          sudo make install
      
      - name: Check for static libraries
        if: false
        run: |
          find /usr/lib/x86_64-linux-gnu -name "libx265.a"
          find /usr/lib/x86_64-linux-gnu/pkgconfig -name "x265.pc"
          find /usr/include -name "x265*.h"
          find /usr/include -name "x265_config.h"

      - name: Clone and build FFmpeg
        run: |
          git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git
          cd ffmpeg
          
          export PKG_CONFIG=/usr/local/bin/pkg-config
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
  
          ./configure --enable-gpl \
            --enable-libx265 \
            --pkg-config=$PKG_CONFIG \
            --enable-libtheora \
            --enable-openssl \
            --enable-nonfree \
            --enable-static \
            --disable-shared \
            --prefix=/usr/local/ff2024 \
            --extra-ldflags="-L/usr/lib/x86_64-linux-gnu -static" \
            

          make -j$(nproc)
          sudo make install
          sudo ldconfig
          ldd /usr/local/ff2024/bin/ffmpeg || true
      
      - name: Clone and build FFmpeg
        if: false
        run: |
          git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git
          cd ffmpeg

          ./configure --enable-gpl \
            --enable-libx264 \
            --enable-libfdk-aac \
            --enable-libmp3lame \
            --enable-libopus \
            --enable-libtheora \
            --enable-libvorbis \
            --enable-libvpx \
            --enable-openssl \
            --enable-nonfree \
            --enable-static \
            --disable-shared \
            --prefix=/usr/local/ff2024 \
            --extra-ldflags="-L/usr/lib/x86_64-linux-gnu -static" \
            --pkg-config-flags="--static"

          make -j$(nproc)
          sudo make install
          sudo ldconfig
          ldd /usr/local/ff2024/bin/ffmpeg || true
      
      - name: Clone FFmpeg
        if: false
        run: |
          git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git
          cd ffmpeg
          
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
          
          ./configure --enable-gpl --enable-libx264 --enable-libfdk-aac --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-openssl --enable-nonfree --enable-static --disable-shared --prefix=/usr/local/ff2024 --pkg-config-flags="--static" 

          make -j$(nproc)
          sudo make install
          sudo ldconfig
          
          ldd /usr/local/ff2024/bin/ffmpeg 
          
          sudo cp /lib/x86_64-linux-gnu/libvpx.so.7 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libssl.so.3 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libcrypto.so.3 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libx264.so.163 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libx265.so.199 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libfdk-aac.so.2 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libmp3lame.so.0 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libopus.so.0 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libtheoraenc.so.1 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libtheoradec.so.1 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libvorbis.so.0 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libvorbisenc.so.2 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libbz2.so.1.0 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/libz.so.1 /usr/local/ff2024/bin/
          sudo cp /lib/x86_64-linux-gnu/liblzma.so.5 /usr/local/ff2024/bin/
     
      - name: Verify FFmpeg installation
        run: |
          /usr/local/ff2024/bin/ffmpeg -version
          echo "Listing files in /usr/local/ff2024:"
          ls -R /usr/local/ff2024  
     
      - name: Upload FFmpeg as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg
          path: /usr/local/ff2024/bin/ffmpeg
