name: Setup Android Environment

on: [push]

jobs:
  setup-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.5

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar unzip lib32stdc++6 lib32z1
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip
        mkdir -p $ANDROID_HOME/cmdline-tools
        mv cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64" "emulator"

    - name: Check Android SDK installation
      run: |
        if [ -d "$ANDROID_HOME" ]; then
          echo "Android SDK is installed at $ANDROID_HOME"
        else
          echo "Android SDK is not installed"
        fi

    - name: Check Android Emulator installation
      run: |
        if [ -x "$(command -v emulator)" ]; then
          echo "Android Emulator is installed"
        else
          echo "Android Emulator is not installed"
        fi

    - name: Check sdkmanager installation
      run: |
        if [ -x "$(command -v sdkmanager)" ]; then
          sdkmanager --list
        else
          echo "sdkmanager is not available"
        fi

    - name: Check adb installation
      run: |
        if [ -x "$(command -v adb)" ]; then
          adb version
        else
          echo "adb is not installed"
        fi

    - name: Start emulator
      run: |
        $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio -no-boot-anim -accel off &
        adb wait-for-device
        adb shell input keyevent 82
