name: Verify Specific Tools

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake build-essential cmake git libtool pkg-config texinfo zlib1g-dev yasm llvm

    - name: Install gas-preprocessor
      run: |
        git clone https://github.com/FFmpeg/gas-preprocessor
        sudo cp gas-preprocessor/gas-preprocessor.pl /usr/local/bin/
        sudo chmod +x /usr/local/bin/gas-preprocessor.pl

    - name: Verify GNU assembler
      run: |
        if command -v as > /dev/null; then
          echo "GNU assembler found at: $(command -v as)"
        else
          echo "GNU assembler not found"
        fi

    - name: Verify gas-preprocessor
      run: |
        if command -v gas-preprocessor.pl > /dev/null; then
          echo "gas-preprocessor found at: $(command -v gas-preprocessor.pl)"
        else
          echo "gas-preprocessor not found"
        fi

    - name: Verify clang
      run: |
        if command -v clang > /dev/null; then
          echo "clang found at: $(command -v clang)"
        else
          echo "clang not found"
        fi

    - name: Verify clang++
      run: |
        if command -v clang++ > /dev/null; then
          echo "clang++ found at: $(command -v clang++)"
        else
          echo "clang++ not found"
        fi

    - name: Verify llvm-nm
      run: |
        if command -v llvm-nm > /dev/null; then
          echo "llvm-nm found at: $(command -v llvm-nm)"
        else
          echo "llvm-nm not found"
        fi

    - name: Verify PATH
      run: |
        echo "Current PATH: $PATH"
